[build]
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[build.environment]
  REACT_APP_SERVER_URL = "https://your-backend-server-url.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 